### ISSUE TITLE
Incorrect number of players in heist

### ISSUE THREAD

**Issue by Ghostyface1337** [Mathicha/PD3-RPC#1]
It seems that while playing solo, even though other players are in the heist with me, the rpc always shows (1 out of 4).

Not sure if this is intended, it makes sense to me that in the menu it would show the size of your party, but in heists I think it should show the amount of players in the heist.

Otherwise awesome mod

**Comment by Mathicha** [comment]
I only play duo with a friend or solo so uh i probably didn't got the right value for matchmaking, I'll look into that

**Comment by Mathicha** [comment]
Fixed it with last update
