### ISSUE TITLE
Game Crashes idk.

### ISSUE THREAD

**Issue by NPe7e** [Mathicha/PD3-RPC#2]
So while speedrunning dirty ice the game was lagging from the beginning and then crashed once I was inside.
It said something about this mod so idk.

ue4ss
ue4ss
ue4ss
main_7ffa4f320000!DiscordMod::on_unreal_init() [G:\PD3\PD3-RPC\DiscordMod\dllmain.cpp:154]
ue4ss
ue4ss
ue4ss
ue4ss
ue4ss
ue4ss
ucrtbase
kernel32
ntdll

**Comment by Mathicha** [comment]
Sorry for ruining your speedrun 
Can you send me the unreal crash report folder? Here or on discord (@mathi)
The folder should be in `%LOCALAPPDATA%/PAYDAY3/Saved/Crashes`

**Comment by NPe7e** [comment]
This ue4ss is what I tried pulling out but idk if you mean just sending the whole file. Then I'll send it in some time fo sho.

**Comment by NPe7e** [comment]
Here's a folder of the crash. Could be useful. And if you want things tested I can try to do some stuff idk...
Also, Idk if it could be it but there could be some performance issues with this mod on. I could be wrong but I thought I'd just put it out there.
[UE4CC-Windows-5E187ABD49E5E8B0C4662DBD6FF7408D_0000.zip](https://github.com/Mathicha/PD3-RPC/files/12875086/UE4CC-Windows-5E187ABD49E5E8B0C4662DBD6FF7408D_0000.zip)

**Comment by Mathicha** [comment]
Should be fixed with last update i hope
