### ISSUE TITLE
Crashes when used with an updated UE4SS v3.01

### ISSUE THREAD

**Issue by NPe7e** [Mathicha/PD3-RPC#3]
So apparently when having this mod with the newer version of UE4SS it crashes most likely due to it being a newer version.
The UE4SS in question being: https://modworkshop.net/mod/47771

Not sure if this is still supported but it'd be nice to get a smol update.

**Comment by Mathicha** [comment]
Yes its a known issue
I'm not really playing PD3 these days so i added HW12Dev as collaborator for the mod bc MoolahNet was the first mod the break the compatibility tho no idea if he is planning to update RPC.
I'll update it myself once i feel like PD3 is worth my game time

**Comment by NPe7e** [comment]
Gotcha! 

If it does get updated could you notify me of that?
(and yes I agree with Payday 3 thang, maybe one day....)

**Comment by Mathicha** [comment]
Hey @NPe7e, i just updated it :slightly_smiling_face:

**Comment by NPe7e** [comment]
we're so back.
